services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      
  backend:
    build: ./backend
    container_name: backend_c
    ports: 
      - '8000:8000'
    volumes:
      - ./backend:/app
    environment:
      - PG_DB=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_HOST=db
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app

volumes:
  pgdata: {}
