# Generated by Django 4.2.2 on 2023-09-16 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='products/')),
                ('name', models.CharField(default=None, max_length=100)),
                ('price', models.IntegerField(default=None)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('New & Featured', 'New & Featured'), ('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids'), ('Sale', 'Sale')], max_length=100)),
                ('position_id', models.IntegerField(null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productsmodel')),
            ],
            options={
                'ordering': ['category', 'position_id'],
            },
        ),
    ]
