name: Backend Python-Django

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        python-version: [3.10.14, 3.11.5, 3.11.6, 3.11.7, 3.12.0, 3.12.1, 3.12.2, 3.12.3]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pip setuptools
          pip install -r requirements.txt

      - name: Run Flake8 (Linting)
        working-directory: ./backend
        run: |
          pip install flake8
          flake8 ./backend

      # - name: Run Tests
      #   run: |
      #     python manage.py test

